PieShopApp-Refactored/PieShopApp/PieShopApp/Models/ErrorViewModel.cs
using System;

namespace PieShopApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PieShopApp-Refactored/PieShopApp/PieShopApp/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PieShopApp.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PieShopApp-Refactored/PieShopApp/PieShopApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PieShopApp.Models;
using PieShopApp.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace PieShopApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private IPieService _pieService;

        public HomeController(ILogger<HomeController> logger, IPieService pieService)
        {
            _logger = logger;
            _pieService = pieService;
        }

        public IActionResult Index()
        {
            CultureInfo eur = CultureInfo.GetCultureInfo("es-ES");
            ViewBag.CurrencyConverter = eur;
            return View(_pieService.GetPiesOfTheWeek());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PieShopApp-Refactored/PieShopApp/PieShopApp/Controllers/PieController.cs
using Microsoft.AspNetCore.Mvc;
using PieShopApp.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace PieShopApp.Controllers
{
    public class PieController : Controller
    {
        private IPieService _pieService;
        private ICategoryService _categoryService;

        public PieController(IPieService pieService, ICategoryService categoryService)
        {
            _pieService = pieService;
            _categoryService = categoryService;
        }
        public IActionResult List(string category)
        {
            CultureInfo eur = CultureInfo.GetCultureInfo("es-ES");
            ViewBag.CurrencyConverter = eur;
            return View(_categoryService.GetPieList(category));
        }

        public IActionResult Details(int? id)
        {
            CultureInfo eur = CultureInfo.GetCultureInfo("es-ES");
            ViewBag.CurrencyConverter = eur;
            var pie = _pieService.GetPieById(id.Value);
            if (pie == null)
            {
                return NotFound();
            }
            return View(pie);
        }
    }
}

PieShopApp-Refactored/PieShopApp/PieShopApp/Views/Contact/Index.cshtml
<h1>Click below to contact us</h1>
<br />
<email address="bojandamcevski@gmail.com" content="Click here"></email>

PieShopApp-Refactored/PieShopApp/PieShopApp/Views/Home/Index.cshtml
@model List<PieViewModel>

<partial name="_Carousel" />

<h2>Pies of the week</h2>
<h4>Our weekly selection - just for you!</h4>

<div class="row">

    @foreach (var pie in Model)
    {
        <partial name="_PieCard" model="pie" />
    }

</div>

PieShopApp-Refactored/PieShopApp/PieShopApp/Views/Pie/Details.cshtml
@model PieViewModel

<h2>@Model.Name</h2>

<div class="thumbnail">
    <img alt="@Model.Name" src="@Model.ImageUrl">
    <div class="caption-full">
        <h3 class="pull-right">@Model.Price.ToString("c", ViewBag.CurrencyConverter)</h3>
        <h3>
            <a href="#">@Model.Name</a>
        </h3>
        <h4>@Model.ShortDescription</h4>
        <p>@Model.LongDescription</p>
        <div class="addToCart">
            @*<p class="button">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                   asp-route-pieId="@Model.IdVM">Add to cart</a>
            </p>*@
        </div>
    </div>
</div>

PieShopApp-Refactored/PieShopApp/PieShopApp/Views/Pie/List.cshtml
@model PieListViewModel

<h1>@Model.CurrentCategory</h1>

@foreach (var pie in Model.Pies)
{
    <partial name="_PieCard" model="pie" />
}

PieShopApp-Refactored/PieShopApp/PieShopApp/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<CategoryViewModel>

<li class="dropdown">
    <a asp-controller="Pie"
       asp-action="Index"
       class="dropdown-toggle" data-toggle="dropdown">Pies<b class="caret"></b></a>
    <ul class="dropdown-menu">
        @foreach (var category in Model)
        {
            <li>
                <a asp-controller="Pie" asp-action="List"
                   asp-route-category="@category.CategoryName">@category.CategoryName</a>
            </li>
        }
        <li class="divider"></li>
        <li>
            <a asp-controller="Pie" asp-action="List" asp-route-Category="">View all pies</a>
        </li>
    </ul>
</li>

PieShopApp-Refactored/PieShopApp/PieShopApp/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

PieShopApp-Refactored/PieShopApp/PieShopApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
    <div class="container">

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Pie" asp-action="List">Pies</a></li>
                        <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
                        @*@await Component.InvokeAsync("ShoppingCartSummary")*@
                        @await Component.InvokeAsync("CategoryMenu")
                        @*<li><a asp-controller="Contact" asp-action="Index">Contact</a></li>*@
                    </ul>
                </div>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" alt="Bethany's Pie Shop'" src="~/Images/bethanylogo.png" />
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

PieShopApp-Refactored/PieShopApp/PieShopApp/Views/Shared/_PieCard.cshtml
@model PieViewModel
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="">
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c", ViewBag.CurrencyConverter)</h3>
            <h3>
                <a asp-controller="Pie"
                   asp-action="Details"
                   asp-route-id="@Model.IdVM">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart">
            @*<p class="button">
                <a class="btn btn-primary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-pieId="@Model.PieId">Add to cart</a>
            </p>*@
        </div>
    </div>
</div>